plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.web' ]
}

application {
    mainClass.set('by.spectrometer.MainApp')
}

dependencies {
    implementation 'org.java-websocket:Java-WebSocket:1.5.4'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation 'com.fazecast:jSerialComm:2.10.4'
    implementation 'org.rxtx:rxtx:2.1.7'
    implementation 'org.java-websocket:Java-WebSocket:1.6.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.20.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}